# Generated by Django 3.2.5 on 2021-10-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_weekly_pickup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
