# Generated by Django 3.2.5 on 2021-10-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_last_weekly_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_weekly_pickup',
        ),
    ]
